sudo: required
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rpm

install:
  - wget -O wp-cli-rpm.spec https://raw.githubusercontent.com/wp-cli/wp-cli-bundle/master/utils/wp-cli-rpm.spec
  - wget -O wp-cli-updaterpm.sh https://raw.githubusercontent.com/wp-cli/wp-cli-bundle/master/utils/wp-cli-updaterpm.sh
  - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb || sudo apt-get install -f

script:
  - bash wp-cli-updaterpm.sh

after_success:
  - |
    ls rpm-src/noarch
    # Get the encrypted private key from the repo settings
    echo $WP_CLI_REPO_DEPLOY_KEY | base64 --decode > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    # Add github's public key
    echo "|1|qPmmP7LVZ7Qbpk7AylmkfR0FApQ=|WUy1WS3F4qcr3R5Sc728778goPw= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
    # Prepare the build directory
    git clone git@github.com:wp-cli/builds.git
    cd builds
    # Prepare git
    git config user.name "Travis CI"
    git config user.email "travis@travis-ci.org"
    git config push.default "current"
    # Copy files into git and commit
    cp -n ../rpm-src/noarch/wp-cli-*.noarch.rpm rpm
    git add rpm
    git commit -m "rpm build"
    git push
