sudo: required
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rpm

install:
  - wget -O wp-cli-rpm.spec https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-cli-rpm.spec
  - wget -O wp-cli-updaterpm.sh https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-cli-updaterpm.sh
  - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/r/rpmlint/rpmlint_1.7-1_all.deb
  - sudo dpkg -i rpmlint_1.7-1_all.deb
  - sudo apt-get install -f

script:
  - bash wp-cli-updaterpm.sh
